# Generated by Django 4.0.4 on 2022-07-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Este blog contiene informacion sobre {{post.title}}', max_length=100),
        ),
    ]
