# Generated by Django 4.0.4 on 2022-07-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
