# Generated by Django 4.0.4 on 2022-07-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_perfil_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
